# Generated by Codex on 2026-04-07

import applications.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_alter_application_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="resumes/",
                validators=[applications.validators.validate_resume],
            ),
        ),
    ]
